version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: test_database_name
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '3306:3306'